//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctoPlusCore.Configuration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OctoPlusCore.Configuration.Resources.ConfigurationStrings", typeof(ConfigurationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache timeout in seconds.
        /// </summary>
        internal static string CacheTimeoutInSeconds {
            get {
                return ResourceManager.GetString("CacheTimeoutInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file was found, but couldn&apos;t be deserialised. Please check the syntax in the file.
        /// </summary>
        internal static string LoadCouldntParseFile {
            get {
                return ResourceManager.GetString("LoadCouldntParseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file could not be loaded.
        /// </summary>
        internal static string LoadErrorCaption {
            get {
                return ResourceManager.GetString("LoadErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No configuration file found. A sample configuration file has been created called &quot;config.json&quot;. Please load this and fill in the settings.
        /// </summary>
        internal static string LoadNoFileFound {
            get {
                return ResourceManager.GetString("LoadNoFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No configuration file found and I couldn&apos;t create a sample file for you. Please configure config.json manually.
        /// </summary>
        internal static string LoadNoFileFoundCantCreate {
            get {
                return ResourceManager.GetString("LoadNoFileFoundCantCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional setting for the default branch name.
        /// </summary>
        internal static string SamepleDefaultEnvironmentName {
            get {
                return ResourceManager.GetString("SamepleDefaultEnvironmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Octopus Deploy API key. You can get this fromPackage your profile page..
        /// </summary>
        internal static string SampleApiKey {
            get {
                return ResourceManager.GetString("SampleApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional setting for the default channel name.
        /// </summary>
        internal static string SampleChannelName {
            get {
                return ResourceManager.GetString("SampleChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project name in Octopus Deploy which has all the channel projectIdOrHrefs you wish to deploy. Used for the drop down.
        /// </summary>
        internal static string SampleChannelSeedAppName {
            get {
                return ResourceManager.GetString("SampleChannelSeedAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base URL of your Octopus Deploy installation.
        /// </summary>
        internal static string SampleOctopusUrl {
            get {
                return ResourceManager.GetString("SampleOctopusUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional string to match project groups on to filter the project list.
        /// </summary>
        internal static string SampleProjectGroupFilterString {
            get {
                return ResourceManager.GetString("SampleProjectGroupFilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default OctoHelper isn&apos;t set, Did you call OctoHelper.Init?.
        /// </summary>
        internal static string ValidationNoDefaultOctoHelper {
            get {
                return ResourceManager.GetString("ValidationNoDefaultOctoHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t speak to Octopus Deploy. Is your URL and API key set correctly?.
        /// </summary>
        internal static string ValidationOctopusApiFailure {
            get {
                return ResourceManager.GetString("ValidationOctopusApiFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Octopus Deploy API key specified in the configuration file.
        /// </summary>
        internal static string ValidationOctopusApiKey {
            get {
                return ResourceManager.GetString("ValidationOctopusApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Octopus Deploy URL specified in the configuration file.
        /// </summary>
        internal static string ValidationOctopusUrl {
            get {
                return ResourceManager.GetString("ValidationOctopusUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No seed project specified. This is needed to pull the available channels fromPackage.
        /// </summary>
        internal static string ValidationSeedProject {
            get {
                return ResourceManager.GetString("ValidationSeedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the seed project specified in the configuration file.
        /// </summary>
        internal static string ValidationSeedProjectNotValid {
            get {
                return ResourceManager.GetString("ValidationSeedProjectNotValid", resourceCulture);
            }
        }
    }
}
