image: microsoft/dotnet:latest

stages:
    - build

variables:
    test: "Example.Test"

before_script:
    - "dotnet restore src/Core"

build:
    stage: build
    script:
        - "dotnet build -c Release src/Core/OctoPlus.sln"
        - "dotnet publish -c Release src/Core/OctoPlus.Console/OctoPlus.Console.csproj -o ../../../octoplus-release"
    artifacts:
        paths:
            - octoplus-release/

publish:
    stage: build
    only: 
        - master
    script:
        - powershell -File "src/Core/package.ps1 '-nugetKey `"$NUGETKEY`"''"