image: microsoft/dotnet:latest

stages:
    - build

variables:
    test: "Example.Test"

before_script:
    - "dotnet restore src/Core"

build:
    stage: build
    script:
        - "dotnet build -c Release src/Core/OctoPlus.sln"
        - "dotnet publish -c Release src/Core/OctoPlus.Console/OctoPlus.Console.csproj -o ../../../octoplus-release"
    artifacts:
        paths:
            - octoplus-release/

publish:
    stage: build
    only: 
        - master
    script:
        - curl -L -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v6.2.0/powershell-6.2.0-linux-x64.tar.gz
        - mkdir -p /opt/microsoft/powershell/6.2.0
        - tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/6.2.0
        - chmod +x /opt/microsoft/powershell/6.2.0/pwsh
        - ln -s /opt/microsoft/powershell/6.2.0/pwsh /usr/bin/pwsh
        - pwsh -File "src/Core/package.ps1 '-nugetKey $NUGETKEY'"