image: microsoft/dotnet:latest

stages:
    - build

variables:
    test: "Example.Test"

before_script:
    - "cd src/Core"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build -c Release OctoPlus.sln"
        - cd OctoPlus.Console
        - "dotnet publish -c Release OctoPlus.Console.csproj -o publish"
    artifacts:
        paths:
            - publish
