//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctoPlusCore.Language.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OctoPlusCore.Language.Resources.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to update the variables for the above releases?.
        /// </summary>
        internal static string AreYouSureUpdateVariables {
            get {
                return ResourceManager.GetString("AreYouSureUpdateVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeLog:.
        /// </summary>
        internal static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking your options....
        /// </summary>
        internal static string CheckingOptions {
            get {
                return ResourceManager.GetString("CheckingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you absolutely 100% sure you wish to delete {0}? There is no going back....
        /// </summary>
        internal static string ConfirmationCheck {
            get {
                return ResourceManager.GetString("ConfirmationCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t add the environment to that team: {0}.
        /// </summary>
        internal static string CouldntAddEnvToTeam {
            get {
                return ResourceManager.GetString("CouldntAddEnvToTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Package.
        /// </summary>
        internal static string CurrentPackage {
            get {
                return ResourceManager.GetString("CurrentPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Release.
        /// </summary>
        internal static string CurrentRelease {
            get {
                return ResourceManager.GetString("CurrentRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version: {0}.
        /// </summary>
        internal static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying channel {0} to {1}. Please select the projects you wish to deploy..
        /// </summary>
        internal static string DeployingTo {
            get {
                return ResourceManager.GetString("DeployingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying using config {0}.
        /// </summary>
        internal static string DeployingUsingConfig {
            get {
                return ResourceManager.GetString("DeployingUsingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done {0}.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download {0} available here: {1}.
        /// </summary>
        internal static string DownloadAvailableHere {
            get {
                return ResourceManager.GetString("DownloadAvailableHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvironmentId: {0}.
        /// </summary>
        internal static string EnvionmentId {
            get {
                return ResourceManager.GetString("EnvionmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment found with name {0}.
        /// </summary>
        internal static string EnvironmentFound {
            get {
                return ResourceManager.GetString("EnvironmentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment not found with name {0}.
        /// </summary>
        internal static string EnvironmentNotFound {
            get {
                return ResourceManager.GetString("EnvironmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You specified {0} columns but the table has {1} headings?.
        /// </summary>
        internal static string ErrorColumnHeadingMismatch {
            get {
                return ResourceManager.GetString("ErrorColumnHeadingMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Package.
        /// </summary>
        internal static string ExistingPackage {
            get {
                return ResourceManager.GetString("ExistingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Release.
        /// </summary>
        internal static string ExistingRelease {
            get {
                return ResourceManager.GetString("ExistingRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting....
        /// </summary>
        internal static string Exiting {
            get {
                return ResourceManager.GetString("Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed {0} : {1}.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed parsing the json file, please check your syntax!.
        /// </summary>
        internal static string FailedParsingVariableFile {
            get {
                return ResourceManager.GetString("FailedParsingVariableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an error from Octopus when updating variables: {0}.
        /// </summary>
        internal static string FailedUpdatingVariableSet {
            get {
                return ResourceManager.GetString("FailedUpdatingVariableSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching project list.
        /// </summary>
        internal static string FetchingProjectList {
            get {
                return ResourceManager.GetString("FetchingProjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces a redeploy of the same packages.
        /// </summary>
        internal static string ForceRedeploy {
            get {
                return ResourceManager.GetString("ForceRedeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting group info.
        /// </summary>
        internal static string GettingGroupInfo {
            get {
                return ResourceManager.GetString("GettingGroupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to rename the following to {0}.
        /// </summary>
        internal static string GoingToRename {
            get {
                return ResourceManager.GetString("GoingToRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No deployment will take place, saving a profile to {0}.
        /// </summary>
        internal static string GoingToSaveProfile {
            get {
                return ResourceManager.GetString("GoingToSaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update: 1 | Remove: 2 | Continue: c | Exit: e.
        /// </summary>
        internal static string InteractiveRunnerInstructions {
            get {
                return ResourceManager.GetString("InteractiveRunnerInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make a selection using ranges 1-2 or comma separated 1,2,3 etc..
        /// </summary>
        internal static string InteractiveRunnerSelectionInstructions {
            get {
                return ResourceManager.GetString("InteractiveRunnerSelectionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release versions much follow the semantic versioning 2.0 spec!.
        /// </summary>
        internal static string InvalidReleaseVersion {
            get {
                return ResourceManager.GetString("InvalidReleaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lifecycle you specified doesn&apos;t exist?.
        /// </summary>
        internal static string LifecycleDoesntExist {
            get {
                return ResourceManager.GetString("LifecycleDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phase number you provided is invalid. Please use a number, like 1 or 2.
        /// </summary>
        internal static string LifecyclePhaseIsInvalid {
            get {
                return ResourceManager.GetString("LifecyclePhaseIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Info for {0}.
        /// </summary>
        internal static string LoadingInfoFor {
            get {
                return ResourceManager.GetString("LoadingInfoFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multi.
        /// </summary>
        internal static string Multi {
            get {
                return ResourceManager.GetString("Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Package.
        /// </summary>
        internal static string NewPackage {
            get {
                return ResourceManager.GetString("NewPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version: {0}.
        /// </summary>
        internal static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version of OctoPlus available.
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No channel found with the specified name! .
        /// </summary>
        internal static string NoMatchingChannel {
            get {
                return ResourceManager.GetString("NoMatchingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No environments match your criteria!.
        /// </summary>
        internal static string NoMatchingEnvironments {
            get {
                return ResourceManager.GetString("NoMatchingEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable package found for step {0} for project {1}.
        /// </summary>
        internal static string NoSuitablePackageFound {
            get {
                return ResourceManager.GetString("NoSuitablePackageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected!.
        /// </summary>
        internal static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On source.
        /// </summary>
        internal static string OnSource {
            get {
                return ResourceManager.GetString("OnSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Target.
        /// </summary>
        internal static string OnTarget {
            get {
                return ResourceManager.GetString("OnTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no package available to deploy for one of the projects you&apos;re trying to select!.
        /// </summary>
        internal static string PackageNotSelectable {
            get {
                return ResourceManager.GetString("PackageNotSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter must be a number.
        /// </summary>
        internal static string ParameterNotANumber {
            get {
                return ResourceManager.GetString("ParameterNotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path doesn&apos;t exist!?.
        /// </summary>
        internal static string PathDoesntExist {
            get {
                return ResourceManager.GetString("PathDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0}.
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile saved to {0}.
        /// </summary>
        internal static string ProfileSaved {
            get {
                return ResourceManager.GetString("ProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided seed project couldn&apos;t be found. I can&apos;t continue!.
        /// </summary>
        internal static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoting from {0} to {1}. Please select the projects you wish to promote..
        /// </summary>
        internal static string PromotingTo {
            get {
                return ResourceManager.GetString("PromotingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to name your release? (Must follow semver, leave blank for sequentially generated).
        /// </summary>
        internal static string ReleaseNamePrompt {
            get {
                return ResourceManager.GetString("ReleaseNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to restrict to certain product groups?.
        /// </summary>
        internal static string RestrictToGroupsPrompt {
            get {
                return ResourceManager.GetString("RestrictToGroupsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeping for {0} seconds....
        /// </summary>
        internal static string SleepingForSeconds {
            get {
                return ResourceManager.GetString("SleepingForSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which environment do you wish to promote from?.
        /// </summary>
        internal static string SourceEnvironment {
            get {
                return ResourceManager.GetString("SourceEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team you specified doesn&apos;t exist?.
        /// </summary>
        internal static string TeamDoesntExist {
            get {
                return ResourceManager.GetString("TeamDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many enviroments match your criteria: .
        /// </summary>
        internal static string TooManyMatchingEnvironments {
            get {
                return ResourceManager.GetString("TooManyMatchingEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error: {0}.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update here: {0}.
        /// </summary>
        internal static string UpdateAvailableHere {
            get {
                return ResourceManager.GetString("UpdateAvailableHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating VariableSet {0} with {1} variables.
        /// </summary>
        internal static string UpdatingVariableSet {
            get {
                return ResourceManager.GetString("UpdatingVariableSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using profile at path .
        /// </summary>
        internal static string UsingProfileAtPath {
            get {
                return ResourceManager.GetString("UsingProfileAtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using profile directory at path.
        /// </summary>
        internal static string UsingProfileDirAtPath {
            get {
                return ResourceManager.GetString("UsingProfileDirAtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for the variable {0} for project {1}. .
        /// </summary>
        internal static string VariablePrompt {
            get {
                return ResourceManager.GetString("VariablePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available values: {0}.
        /// </summary>
        internal static string VariablePromptAllowedValues {
            get {
                return ResourceManager.GetString("VariablePromptAllowedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which channel do you wish to deploy?.
        /// </summary>
        internal static string WhichChannelPrompt {
            get {
                return ResourceManager.GetString("WhichChannelPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which environment do you wish to deploy to?.
        /// </summary>
        internal static string WhichEnvironmentPrompt {
            get {
                return ResourceManager.GetString("WhichEnvironmentPrompt", resourceCulture);
            }
        }
    }
}
